package Entities;
// Generated Jan 15, 2019 8:14:37 PM by Hibernate Tools 4.3.1



/**
 * Etudiant generated by hbm2java
 */
public class Etudiant  implements java.io.Serializable {


     private String idEtudiant;
     private String nom;
     private String prenom;
     private String filiere;

    public Etudiant() {
    }

    public Etudiant(String idEtudiant, String nom, String prenom, String filiere) {
       this.idEtudiant = idEtudiant;
       this.nom = nom;
       this.prenom = prenom;
       this.filiere = filiere;
    }
   
    public String getIdEtudiant() {
        return this.idEtudiant;
    }
    
    public void setIdEtudiant(String idEtudiant) {
        this.idEtudiant = idEtudiant;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }
    public String getFiliere() {
        return this.filiere;
    }
    
    public void setFiliere(String filiere) {
        this.filiere = filiere;
    }




}


